name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Elm environment
      uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1
    - name: Test
      run: npx elm-test
    - name: Check documentation
      run: elm make --docs=docs.json
    - name: Verify documentation
      run: npx elm-verify-examples --run-tests
